### ISSUE TITLE
This account doen't exist

### ISSUE THREAD

**Issue by JAB33699** [augustogoncalves/data.management-csharp-sample#4]
Hi Augusto,

many thanks for this example.
I tried that and i faced a problem.
The response Status is Not Found. Errormessage = This account doesn't exist.
 

```           
m_RestClient = new RestClient("https://developer.api.autodesk.com");
m_Request = new RestRequest("/hq/v1/accounts/{account_id}/users", Method.GET);
m_Request.AddParameter("account_id", CP.Forge.Utilities.Credentials.CompanyAccountID, ParameterType.UrlSegment);
m_Request.AddHeader("Authorization", "Bearer " + m_TokenResponse.Result.AccessToken);
m_Request.AddHeader("Content-Type", "application/json");
//request.AddParameter("application/json", body, ParameterType.RequestBody);
IRestResponse response = m_RestClient.Execute<CP.Forge.Utilities.AccessToken>(m_Request);
```

What is wrong.

I checked the BIM 360 account id several time and seems ok.

Cheers Jürgen

**Comment by augustogoncalves** [comment]
When you debug the code, what's the account ID value (on the code)?

**Comment by JAB33699** [comment]
Hi Augusto,
thanks for Reply.
It is the BIM 360 ID of the customer. It's ok, Looks like a guid.
Cheers Jürgen

**Comment by augustogoncalves** [comment]
I would suspect (1) wrong formatting (probably not as the code reads it) or (2) missing permission for this request. 

have you tried the same request on *Postman*?

**Comment by JAB33699** [comment]
We are using the BIM account id which is mentioned in the Add Custom Integration Dialog.

I will try it with postman.

**Comment by JAB33699** [comment]
Hi Augusto,

the base URL is: https://developer.api.autodesk.com
the request URL is: 
/hq/v1/accounts/2d41ff0d-9618-473a-####-#############/users

AccessToken: Id = 33, Status = **RanToCompletion**, Method = "{null}", Result = "Autodesk.ADN.Toolkit.ViewData.DataContracts.TokenResponse"

What does RanToCompletion means?

Cheers Jürgen

**Comment by augustogoncalves** [comment]
this is unexpected... I don't use any `Toolkit` on this sample... not sure what you changed here. 

back to your original question, I see you try cast the response to `CP.Forge.Utilities.AccessToken`, but it should be something like the response with list of users, so it cannot be converted... and I guess some other change is causing the 404 error you got. 

and, BTW, `RanToCompletion` means your `async` request is not yet complete

**Comment by JAB33699** [comment]
Now it's look the following.

```
m_RestClient = new RestClient("https://developer.api.autodesk.com");
m_Request = new RestRequest(string.Format("/hq/v1/accounts/{0}/users",   CP.Forge.Utilities.Credentials.CompanyAccountID),  Method.GET);
//m_Request.AddParameter("account_id", CP.Forge.Utilities.Credentials.CompanyAccountID, ParameterType.UrlSegment);
m_Request.AddHeader("Authorization", "Bearer " + m_TokenResponse.Result.AccessToken);
m_Request.AddHeader("Content-Type", "application/json");
IRestResponse response = await m_RestClient.ExecuteTaskAsync(m_Request);
```

doesn't work.
I think this is the original one!?

RanToCompletion: Maybe thsat is the problem.

**Comment by augustogoncalves** [comment]
and what's the `response` value?

**Comment by JAB33699** [comment]
Content: "{\"code\":1004,\"message\":\"this account doesn't exist.\"}"

Value doesn't exist.

**Comment by JAB33699** [comment]
What account does they mean?
Our account id starts with 2d41ff0d-9618 etc.
