### ISSUE TITLE
Error : 400 - Invalid redirect_uri

### ISSUE THREAD

**Issue by DanTartagliaNBBJ** [augustogoncalves/data.management-csharp-sample#5]
Hi Augusto,
I'm new to Forge, all I did was download the csharp-example, change FORGE_CLIENT_ID and FORGE_CLIENT_SECRET. When I compile/run I get:
Oops
Error : 400 - Invalid redirect_uri
We're experiencing problems with the application configuration.
Connecting Application
Please try again later.
Then tried using the callback URL with my app, get the same message. Just using VS. Any suggestions?
Thanks,
Dan

**Comment by augustogoncalves** [comment]
For local testing, please use the same callback URL you used on Forge Dev Portal and here

https://github.com/Autodesk-Forge/data.management-csharp-sample/blob/master/data.management-csharp-sample/Web.config#L28

**Comment by DanTartagliaNBBJ** [comment]
Hi Augusto,

I am using the URL:
<add key="FORGE_CALLBACK_URL" value="http://localhost:3000/api/forge/callback/oauth" />
...but get the same error message. I created a Forge app and using the given FORGE_CLIENT_ID and FORGE_CLIENT_SECRET.

**Comment by augustogoncalves** [comment]
not sure if this still an open questions, in any case, please check http://learnforge.autodesk.io/#/account/?id=create-an-app

**Comment by jmcouffin** [comment]
if in Heroku:
![image](https://user-images.githubusercontent.com/7872003/133047176-84ac1559-d782-4d5d-97d1-0341c5e3a80b.png)

**Comment by akhid** [comment]
> For local testing, please use the same callback URL you used on Forge Dev Portal and here
> 
> https://github.com/Autodesk-Forge/data.management-csharp-sample/blob/master/data.management-csharp-sample/Web.config#L28

Hi this link is not works.
I've the same problem.
use Visual Studio 2022, .net 6. following tutorial from https://tutorials.autodesk.io/tutorials/hubs-browser/auth
